version: '3'
services:
  # mysql-db: 
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: super
  #     MYSQL_DATABASE: database_development
  #     MYSQL_USER: man
  #     MYSQL_PASSWORD: super
  #   ports: 
  #     - "3306:3306"
  #   expose:
  #     - "3306"
  #   volumes:
  #     - db_data:/var/lib/mysql
  app:
    build: ./server
    volumes:
      - ./server:/usr/app/
    ports:
      - "8082:8082"


