version: '3'

services:
  mysql-db: 
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpwd
    restart: always
    ports: 
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    volumes:
      - ./server:/usr/app/
    ports:
      - 8082:8082
volumes:
  db_data:


