version: '3'

services:
  mysql-db: 
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: arrow
    ports: 
      - 3306:3306
    volumes:
      - ${PWD}/migrations/sequelize:/sql
  app:
    context: ./server
    dockerfile: Dockerfile
    depends_on:
      - mysql-db
    volumes:
      - ./server:/usr/app/
    ports:
      - 8082:8082


