version: '3'

services:
  mysql-db: 
    image: mysql
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpwd
       MYSQL_DATABASE: dev_db
    restart: always
    ports: 
      - 3306:3306
    volumes:
      - ${PWD}/migrations/sequelize:/sql
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    volumes:
      - ./server:/usr/app/
    ports:
      - 8082:8082


