version: '3'

services:
  mysql-db: 
    image: mysql
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: super
       MYSQL_PASSWORD: man
       MYSQL_DATABASE: database_development
    restart: always
    ports: 
      - 3306:3306
    volumes:
      - ${PWD}/migrations/sequelize:/sql
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
      command: ['./server/wait-for-it.sh','mysql-db:3306','npm start']
    depends_on:
      - mysql-db
    volumes:
      - ./server:/usr/app/
    ports:
      - 8082:8082


